# Generated by Django 4.1.2 on 2022-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pesel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
