# Generated by Django 4.1.2 on 2022-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dca_app', '0002_patient_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.IntegerField(unique=True),
        ),
    ]
